def main():
    cities = [
        "New York, NY", "Los Angeles, CA", "Chicago, IL", "Houston, TX", "Phoenix, AZ",
        "Philadelphia, PA", "San Antonio, TX", "San Diego, CA", "Dallas, TX", "San Jose, CA",
        "Austin, TX", "Jacksonville, FL", "Fort Worth, TX", "Columbus, OH", "San Francisco, CA",
        "Charlotte, NC", "Indianapolis, IN", "Seattle, WA", "Denver, CO", "Washington, DC",
        "Boston, MA", "El Paso, TX", "Nashville, TN", "Detroit, MI", "Oklahoma City, OK",
        "Portland, OR", "Las Vegas, NV", "Louisville, KY", "Baltimore, MD", "Milwaukee, WI",
        "Albuquerque, NM", "Tucson, AZ", "Fresno, CA", "Sacramento, CA", "Long Beach, CA",
        "Kansas City, MO", "Mesa, AZ", "Virginia Beach, VA", "Atlanta, GA", "Colorado Springs, CO",
        "Omaha, NE", "Raleigh, NC", "Miami, FL", "Cleveland, OH", "Tulsa, OK",
        "Oakland, CA", "Minneapolis, MN", "Wichita, KS", "New Orleans, LA", "Arlington, TX",
        "Bakersfield, CA", "Tampa, FL", "Honolulu, HI", "Anaheim, CA", "Santa Ana, CA",
        "Corpus Christi, TX", "Riverside, CA", "St. Louis, MO", "Lexington, KY", "Stockton, CA",
        "Pittsburgh, PA", "Anchorage, AK", "Cincinnati, OH", "Henderson, NV", "Greensboro, NC",
        "Plano, TX", "Newark, NJ", "Chula Vista, CA", "Toledo, OH", "Orlando, FL",
        "Champaign, IL", "Santa Clarita, CA", "Baton Rouge, LA", "Irvine, CA", "Durham, NC",
        "Laredo, TX", "Chandler, AZ", "Madison, WI", "Lubbock, TX", "Scottsdale, AZ",
        "Reno, NV", "Glendale, AZ", "Hialeah, FL", "Garland, TX", "Chesapeake, VA",
        "Irving, TX", "Gilbert, AZ", "Birmingham, AL", "Richmond, VA", "Boise, ID",
        "San Bernardino, CA", "Spokane, WA", "Des Moines, IA", "Modesto, CA", "Fremont, CA",
        "Santa Rosa, CA", "Montgomery, AL", "Augusta, GA", "Akron, OH", "Little Rock, AR",
        "Colontown, TX", "Springfield, IL", "Memphis, TN", "Peoria, IL", "Huntington Beach, CA", 
        "Grand Rapids, MI", "Salt Lake City, UT", "Tallahassee, FL", "New Haven, CT"
    ]

    distances = {
        ("Champaign, IL", "Chicago, IL"): 135,
        ("Champaign, IL", "Indianapolis, IN"): 120,
        ("Champaign, IL", "St. Louis, MO"): 180,
        ("Champaign, IL", "Peoria, IL"): 90,
        ("Champaign, IL", "Springfield, IL"): 100,
        ("New York, NY", "Los Angeles, CA"): 2790,
        ("New York, NY", "Chicago, IL"): 790,
        ("New York, NY", "Houston, TX"): 1628,
        ("New York, NY", "Phoenix, AZ"): 2145,
        ("New York, NY", "Philadelphia, PA"): 95,
        ("New York, NY", "San Antonio, TX"): 1790,
        ("New York, NY", "San Diego, CA"): 2829,
        ("New York, NY", "Dallas, TX"): 1548,
        ("New York, NY", "San Jose, CA"): 2904,
        ("New York, NY", "Austin, TX"): 1745,
        ("New York, NY", "New Haven, CT"): 85,
        ("Los Angeles, CA", "Chicago, IL"): 2015,
        ("Los Angeles, CA", "Houston, TX"): 1547,
        ("Los Angeles, CA", "Phoenix, AZ"): 373,
        ("Los Angeles, CA", "Philadelphia, PA"): 2715,
        ("Los Angeles, CA", "San Antonio, TX"): 1356,
        ("Los Angeles, CA", "San Diego, CA"): 120,
        ("Los Angeles, CA", "Dallas, TX"): 1435,
        ("Los Angeles, CA", "San Jose, CA"): 340,
        ("Los Angeles, CA", "Austin, TX"): 1377,
        ("Chicago, IL", "Houston, TX"): 1083,
        ("Chicago, IL", "Phoenix, AZ"): 1753,
        ("Chicago, IL", "Philadelphia, PA"): 759,
        ("Chicago, IL", "San Antonio, TX"): 1182,
        ("Chicago, IL", "San Diego, CA"): 2060,
        ("Chicago, IL", "Dallas, TX"): 967,
        ("Houston, TX", "Phoenix, AZ"): 1175,
        ("Houston, TX", "Philadelphia, PA"): 1546,
        ("Houston, TX", "San Antonio, TX"): 197,
        ("Phoenix, AZ", "Philadelphia, PA"): 2075,
        ("Phoenix, AZ", "San Antonio, TX"): 1000,
        ("Phoenix, AZ", "San Diego, CA"): 355,
        ("Phoenix, AZ", "Dallas, TX"): 1065,
        ("Phoenix, AZ", "San Jose, CA"): 725,
        ("Phoenix, AZ", "Austin, TX"): 1000,
        ("Philadelphia, PA", "San Antonio, TX"): 1700,
        ("Philadelphia, PA", "San Diego, CA"): 2700,
        ("Philadelphia, PA", "Dallas, TX"): 1500,
        ("Philadelphia, PA", "San Jose, CA"): 2900,
        ("Philadelphia, PA", "Austin, TX"): 1600,
        ("San Antonio, TX", "San Diego, CA"): 1200,
        ("San Antonio, TX", "Dallas, TX"): 275,
        ("San Antonio, TX", "San Jose, CA"): 1500,
        ("San Antonio, TX", "Austin, TX"): 80,
        ("San Diego, CA", "Dallas, TX"): 1350,
        ("San Diego, CA", "San Jose, CA"): 450,
        ("San Diego, CA", "Austin, TX"): 1300,
        ("Dallas, TX", "San Jose, CA"): 1700,
        ("Dallas, TX", "Austin, TX"): 200,
        ("San Jose, CA", "Austin, TX"): 1500,
        ("Boston, MA", "El Paso, TX"): 2300,
        ("Boston, MA", "Nashville, TN"): 1100,
        ("Boston, MA", "Detroit, MI"): 700,
        ("Boston, MA", "Oklahoma City, OK"): 1700,
        ("Boston, MA", "Portland, OR"): 3100,
        ("El Paso, TX", "Nashville, TN"): 1400,
        ("El Paso, TX", "Detroit, MI"): 1800,
        ("El Paso, TX", "Oklahoma City, OK"): 700,
        ("El Paso, TX", "Portland, OR"): 1600,
        ("Nashville, TN", "Detroit, MI"): 500,
        ("Nashville, TN", "Oklahoma City, OK"): 700,
        ("Nashville, TN", "Portland, OR"): 2300,
        ("Detroit, MI", "Oklahoma City, OK"): 1100,
        ("Detroit, MI", "Portland, OR"): 2300,
        ("Oklahoma City, OK", "Portland, OR"): 2000,
        ("Portland, OR", "Las Vegas, NV"): 1000,
        ("Portland, OR", "Louisville, KY"): 2200,
        ("Portland, OR", "Baltimore, MD"): 2800,
        ("Portland, OR", "Milwaukee, WI"): 2000,
        ("Las Vegas, NV", "Louisville, KY"): 1800,
        ("Las Vegas, NV", "Baltimore, MD"): 2400,
        ("Las Vegas, NV", "Milwaukee, WI"): 1800,
        ("Louisville, KY", "Baltimore, MD"): 600,
        ("Louisville, KY", "Milwaukee, WI"): 400,
        ("Baltimore, MD", "Milwaukee, WI"): 800,
        ("Albuquerque, NM", "Tucson, AZ"): 320,
        ("Albuquerque, NM", "Fresno, CA"): 800,
        ("Albuquerque, NM", "Sacramento, CA"): 900,
        ("Albuquerque, NM", "Long Beach, CA"): 800,
        ("Albuquerque, NM", "Kansas City, MO"): 800,
        ("Tucson, AZ", "Fresno, CA"): 600,
        ("Tucson, AZ", "Sacramento, CA"): 700,
        ("Tucson, AZ", "Long Beach, CA"): 500,
        ("Tucson, AZ", "Kansas City, MO"): 1100,
        ("Fresno, CA", "Sacramento, CA"): 200,
        ("Fresno, CA", "Long Beach, CA"): 250,
        ("Fresno, CA", "Kansas City, MO"): 1500,
        ("Sacramento, CA", "Long Beach, CA"): 400,
        ("Sacramento, CA", "Kansas City, MO"): 1600,
        ("Long Beach, CA", "Kansas City, MO"): 1500,
        ("Kansas City, MO", "Mesa, AZ"): 1200,
        ("Kansas City, MO", "Virginia Beach, VA"): 1300,
        ("Kansas City, MO", "Atlanta, GA"): 800,
        ("Kansas City, MO", "Colorado Springs, CO"): 600,
        ("Mesa, AZ", "Virginia Beach, VA"): 2300,
        ("New York, NY", "Miami, FL"): 1280,
        ("Los Angeles, CA", "Seattle, WA"): 1135,
        ("Chicago, IL", "Atlanta, GA"): 715,
        ("Houston, TX", "Denver, CO"): 1020,
        ("Phoenix, AZ", "Portland, OR"): 1335,
        ("Philadelphia, PA", "Boston, MA"): 310,
        ("San Antonio, TX", "Las Vegas, NV"): 1275,
        ("San Diego, CA", "Salt Lake City, UT"): 750,
        ("Dallas, TX", "Minneapolis, MN"): 940,
        ("San Jose, CA", "Kansas City, MO"): 1800,
        ("Austin, TX", "Nashville, TN"): 820,
        ("Jacksonville, FL", "Columbus, OH"): 780,
        ("Fort Worth, TX", "Charlotte, NC"): 980,
        ("Columbus, OH", "Indianapolis, IN"): 175,
        ("San Francisco, CA", "Denver, CO"): 1250,
        ("Charlotte, NC", "Seattle, WA"): 2400,
        ("Indianapolis, IN", "Washington, DC"): 580,
        ("Seattle, WA", "Denver, CO"): 1300,
        ("Denver, CO", "Washington, DC"): 1670,
        ("Washington, DC", "Boston, MA"): 440,
        ("Boston, MA", "El Paso, TX"): 2300,
        ("El Paso, TX", "Nashville, TN"): 1400,
        ("Nashville, TN", "Detroit, MI"): 500,
        ("Detroit, MI", "Oklahoma City, OK"): 1100,
        ("Oklahoma City, OK", "Portland, OR"): 2000,
        ("Portland, OR", "Las Vegas, NV"): 1000,
        ("Las Vegas, NV", "Louisville, KY"): 1800,
        ("Louisville, KY", "Baltimore, MD"): 600,
        ("Baltimore, MD", "Milwaukee, WI"): 800,
        ("Milwaukee, WI", "Albuquerque, NM"): 1300,
        ("Albuquerque, NM", "Tucson, AZ"): 320,
        ("Albuquerque, NM", "Fresno, CA"): 800,
        ("Albuquerque, NM", "Sacramento, CA"): 900,
        ("Albuquerque, NM", "Long Beach, CA"): 800,
        ("Albuquerque, NM", "Kansas City, MO"): 800,
        ("Tucson, AZ", "Fresno, CA"): 600,
        ("Tucson, AZ", "Sacramento, CA"): 700,
        ("Tucson, AZ", "Long Beach, CA"): 500,
        ("Tucson, AZ", "Kansas City, MO"): 1100,
        ("Fresno, CA", "Sacramento, CA"): 200,
        ("Fresno, CA", "Long Beach, CA"): 250,
        ("Fresno, CA", "Kansas City, MO"): 1500,
        ("Sacramento, CA", "Long Beach, CA"): 400,
        ("Sacramento, CA", "Kansas City, MO"): 1600,
        ("Long Beach, CA", "Kansas City, MO"): 1500,
        ("Kansas City, MO", "Mesa, AZ"): 1200,
        ("Kansas City, MO", "Virginia Beach, VA"): 1300,
        ("Kansas City, MO", "Atlanta, GA"): 800,
        ("Kansas City, MO", "Colorado Springs, CO"): 600,
        ("Mesa, AZ", "Virginia Beach, VA"): 2300,
        ("New York, NY", "Orlando, FL"): 1090,
        ("Los Angeles, CA", "San Francisco, CA"): 380,
        ("Chicago, IL", "Miami, FL"): 1375,
        ("Houston, TX", "Atlanta, GA"): 800,
        ("Phoenix, AZ", "Las Vegas, NV"): 300,
        ("Philadelphia, PA", "Cleveland, OH"): 430,
        ("San Antonio, TX", "Oklahoma City, OK"): 420,
        ("San Diego, CA", "San Francisco, CA"): 500,
        ("Dallas, TX", "Denver, CO"): 780,
        ("San Jose, CA", "Salt Lake City, UT"): 850,
        ("Austin, TX", "Memphis, TN"): 600,
        ("Jacksonville, FL", "Indianapolis, IN"): 720,
        ("Fort Worth, TX", "Louisville, KY"): 800,
        ("Columbus, OH", "Charlotte, NC"): 400,
        ("San Francisco, CA", "Seattle, WA"): 800,
        ("Charlotte, NC", "Denver, CO"): 1600,
        ("Indianapolis, IN", "Boston, MA"): 850,
        ("Seattle, WA", "Houston, TX"): 2300,
        ("Denver, CO", "Miami, FL"): 2050,
        ("Washington, DC", "Detroit, MI"): 520,
        ("Boston, MA", "Phoenix, AZ"): 2300,
        ("El Paso, TX", "San Diego, CA"): 725,
        ("Nashville, TN", "Minneapolis, MN"): 900,
        ("Detroit, MI", "Dallas, TX"): 1100,
        ("Oklahoma City, OK", "Las Vegas, NV"): 1100,
        ("Portland, OR", "San Antonio, TX"): 1800,
        ("Las Vegas, NV", "Miami, FL"): 2500,
        ("Louisville, KY", "New Orleans, LA"): 700,
        ("Baltimore, MD", "Atlanta, GA"): 680,
        ("Milwaukee, WI", "Houston, TX"): 1175,
        ("Albuquerque, NM", "Denver, CO"): 450,
        ("Albuquerque, NM", "Salt Lake City, UT"): 600,
        ("Albuquerque, NM", "Las Vegas, NV"): 575,
        ("Albuquerque, NM", "Phoenix, AZ"): 420,
        ("Tucson, AZ", "El Paso, TX"): 320,
        ("Tucson, AZ", "San Antonio, TX"): 850,
        ("Tucson, AZ", "Dallas, TX"): 950,
        ("Tucson, AZ", "Austin, TX"): 850,
        ("Fresno, CA", "Seattle, WA"): 900,
        ("Fresno, CA", "Portland, OR"): 700,
        ("Fresno, CA", "Las Vegas, NV"): 400,
        ("Fresno, CA", "Phoenix, AZ"): 500,
        ("Sacramento, CA", "Seattle, WA"): 750,
        ("Sacramento, CA", "Portland, OR"): 580,
        ("Long Beach, CA", "Seattle, WA"): 1150,
        ("Long Beach, CA", "Portland, OR"): 950,
        ("Kansas City, MO", "Salt Lake City, UT"): 1100,
        ("Kansas City, MO", "Denver, CO"): 600,
        ("Kansas City, MO", "Las Vegas, NV"): 1200,
        ("Kansas City, MO", "Phoenix, AZ"): 1100,
        ("Mesa, AZ", "Denver, CO"): 800,
        ("Mesa, AZ", "Salt Lake City, UT"): 600,
        ("Mesa, AZ", "Las Vegas, NV"): 300,
        ("Mesa, AZ", "Portland, OR"): 1200,
        ("Virginia Beach, VA", "Miami, FL"): 900,
        ("Virginia Beach, VA", "Orlando, FL"): 700,
        ("Virginia Beach, VA", "Atlanta, GA"): 600,
        ("Virginia Beach, VA", "New Orleans, LA"): 1000,
        ("Atlanta, GA", "Salt Lake City, UT"): 1800,
        ("Atlanta, GA", "Denver, CO"): 1400,
        ("Colorado Springs, CO", "Miami, FL"): 2000,
        ("Colorado Springs, CO", "Orlando, FL"): 1900,
        ("Colorado Springs, CO", "Atlanta, GA"): 1400,
        ("Colorado Springs, CO", "New Orleans, LA"): 1300,
        ("Omaha, NE", "Miami, FL"): 1600,
        ("Omaha, NE", "Orlando, FL"): 1500,
        ("Omaha, NE", "Atlanta, GA"): 1000,
        ("Omaha, NE", "New Orleans, LA"): 900,
        ("Raleigh, NC", "Salt Lake City, UT"): 2000,
        ("Raleigh, NC", "Denver, CO"): 1600,
        ("Miami, FL", "Salt Lake City, UT"): 2300,
        ("Miami, FL", "Denver, CO"): 2050,
        ("Cleveland, OH", "Salt Lake City, UT"): 1700,
        ("Cleveland, OH", "Denver, CO"): 1300,
        ("Tulsa, OK", "Salt Lake City, UT"): 1200,
        ("Tulsa, OK", "Denver, CO"): 700,
        ("Oakland, CA", "Salt Lake City, UT"): 750,
        ("Oakland, CA", "Denver, CO"): 1250,
        ("Minneapolis, MN", "Salt Lake City, UT"): 1300,
        ("Minneapolis, MN", "Denver, CO"): 900,
        ("Wichita, KS", "Salt Lake City, UT"): 950,
        ("Wichita, KS", "Denver, CO"): 500,
        ("New Orleans, LA", "Salt Lake City, UT"): 1700,
        ("New Orleans, LA", "Denver, CO"): 1300,
        ("Arlington, TX", "Salt Lake City, UT"): 1100,
        ("Arlington, TX", "Denver, CO"): 780,
        ("Bakersfield, CA", "Salt Lake City, UT"): 650,
        ("Bakersfield, CA", "Denver, CO"): 1100,
        ("Tampa, FL", "Salt Lake City, UT"): 2200,
        ("Tampa, FL", "Denver, CO"): 2050
    }

    # Example of how to use the Graph class
    from graphs import Graph, noPathError

    graph = Graph()
    for city in cities:
        graph.add_node(city)

    for (city1, city2), distance in distances.items():
        graph.add_edge(city1, city2, distance)

    # Example usage of graph methods
    city1 = "Champaign, IL"
    city2 = "Arlington, TX"
    print()
    print(f"Neighbors of {city1}:", graph.get_neighbors(city1))
    print()
    #print("Edge exists between Champaign, IL and Chicago, IL:", graph.has_edge("Champaign, IL", "Chicago, IL"))
    #print("Distance between Champaign, IL and Chicago, IL:", graph.get_edge_weight("Champaign, IL", "Chicago, IL"))
    #print(f"All places that can be reached from {city1}: {graph.bfs(city1)}")
    if(city2 not in graph.bfs(city1)):
        print(f"No path between {city1} and {city2}")
    print(f"Route from {city1} to {city2}: {graph.bfs(city1, city2)}")
    print()
    print("Route length: ", graph.get_path_cost(graph.bfs(city1, city2)), "mi")
    print(graph.adjacency_list)
    print()
    
if __name__ == "__main__":
    main()